//过滤
const FILTER={
    OPTION:'OPTION',
    SET_START_TIME:'FILTER_START_TIME',
    SET_END_TIME:'FILTER_END_TIME',
    SET_USERNUMBER:'FILTER_USER_NUMBER'
}
//顶部筛选条件action Type
const OPTION={
    ADD:'ADD_OPTION',
    CHANGE_CHECK:'OPTION_CHANGE_CHECK'
}

const DATA={
    CANCEL:'DATA_CANCEL',
    ADD_REQUEST:'DATA_ADD_REQUEST',
    ADD_RECEIVE:'DATA_ADD_RECEIVE',
    DATE_DELETE:'DATA_DELETE',
    MAPPING:'DATA_MAPPING',
    DELETE_MAPPING:'DELETE_DATA_MAPPING',
    MD5_COLLECTOR:'DATA_COLLECTOR_MD5',
    MA5_DELETE_COLLECTOR:'MD5_DELETE_COLLECTOR',
    DATE_COLLECTOR:'DATA_COLLECTOR_DATE',
    DATE_DELETE_COLLECTOR:'DATE_DELETE_COLLECTOR',
    INIT_TIME_INDEX:'INIT_TIME_INDEX',
    LOAD_ONETRACK_DETAIL:'LOAD_ONETRACK_DETAIL'
}

//UI
const UI={
    TOPSHOW:'IS_TOP_SHOW',
    DETAILSHOW:'IS_DETAIL_SHOW',
    LOADWAIT:'IS_LOAD_WAIT'
}




export default {
    OPTION,FILTER,UI,DATA

}